TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a

BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMG_HEADER_VERSION := 3
BOARD_MKBOOTIMG_ARGS := --header_version 3
BOARD_RAMDISK_OFFSET := 0x00000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x00000000

TARGET_BOARD_PLATFORM := mt6761
TARGET_BOOTLOADER_BOARD_NAME := tb8766p1_64_bsp

BOARD_SUPER_PARTITION_SIZE := 5368709120
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
TW_INCLUDE_FASTBOOTD := true

TW_USE_MINUI_WITH_DRM := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255

PB_BUILD_IN_SRC := true
PB_THEME := DARK
PB_ENTRY_KEY := 115
PB_DISABLE_AUTO_MOUNT := true
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_REPACKTOOLS := true
